In [15]:
# Import the necessary libraries before you start to work.
import os
import requests
import pandas as pd
import json
import pytz
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# Access the API key.
API_key = os.getenv('OpenWeather_API_key')

# Make a list of the locations you would like to obtain weather data for.

London - 51.6553, -0.396
Truro, Cornwall - 50.2633173, -5.0518107,
Cairo - 30.0443879, 31.2357257

# Decide on the years you would like to explore for comparison and convert the historical years to Unix timestamps for use in your OpenWeather API call 

1990 - 642353567
2023 - 1683732767

In [16]:
# Create an API call.
coordinates = "http://api.openweathermap.org/geo/1.0/direct?q=Truro&limit=1" "&appid=" + API_key

resp3 = requests.get(coordinates)
print("Cornwall coordinates:", resp3.json())

Cornwall coordinates: [{'name': 'Truro', 'local_names': {'kw': 'Truru', 'el': 'Τρούρο', 'sr': 'Труро', 'ru': 'Труро', 'ur': 'ٹرورو', 'hu': 'Truro', 'ar': 'ترورو', 'uk': 'Труро', 'mk': 'Труро', 'br': 'Truru', 'en': 'Truro'}, 'lat': 50.2633173, 'lon': -5.0518107, 'country': 'GB', 'state': 'England'}]

In [17]:
# Set the API endpoint URL and API key.
endpoint_url = "https://api.openweathermap.org/data/3.0/onecall"

# Define a list of coordinates for different locations
locations = [
    {'name': 'London', 'lat': 51.6553, 'lon': -0.396},
    {'name': 'Truro', 'lat': 50.2633173, 'lon': -5.0518107},
    {'name': 'Cairo', 'lat': 30.0443879, 'lon': 31.2357257},
]

# Create an empty list to store the weather data for each location.
weather_data = []

# Loop through each location and get its weather data.
for loc in locations:
    # Set the API parameters.
    params = {
        "lat": loc['lat'],
        "lon": loc['lon'],
        "units": "metric",
        "exclude": "minutely,hourly,daily",
        "appid": API_key
    }

    # Send a GET request to the API endpoint and store the response.
    response = requests.get(endpoint_url, params=params)

    # Access the current weather data.
    current = response.json()['current']

    # Extract the relevant weather information.
    humidity = current['humidity']
    pressure = current['pressure']
    wind = current['wind_speed']
    description = current['weather'][0]['description']
    temp = int(round(current['temp']))
    sunrise = datetime.fromtimestamp(current['sunrise'], tz=pytz.utc).astimezone(pytz.timezone('Europe/London'))
    sunset = datetime.fromtimestamp(current['sunset'], tz=pytz.utc).astimezone(pytz.timezone('Europe/London'))

    # Add the weather data to the list.
    weather_data.append({
        'Location': loc['name'],
        'Temperature (°C)': temp,
        'Wind Speed (m/s)': wind,
        'Pressure (hPa)': pressure,
        'Humidity (%)': humidity,
        'Description': description,
        'Sunrise': sunrise,
        'Sunset': sunset
    })

# Print the weather data in a tabular format.
print("Location\tTemperature (°C)\tWind Speed (m/s)\tPressure (hPa)\tHumidity (%)\tDescription\tSunrise\t\t\t\tSunset")
for data in weather_data:
    print(f"{data['Location']}\t\t{data['Temperature (°C)']}\t\t{data['Wind Speed (m/s)']}\t\t{data['Pressure (hPa)']}\t\t{data['Humidity (%)']}\t\t{data['Description']}\t{data['Sunrise'].strftime('%Y-%m-%d %H:%M:%S')}\t{data['Sunset'].strftime('%Y-%m-%d %H:%M:%S')}")

Location	Temperature (°C)	Wind Speed (m/s)	Pressure (hPa)	Humidity (%)	Description	Sunrise				Sunset
London		16		4.12		1008		75		light rain	2023-05-10 05:17:39	2023-05-10 20:38:24
Truro		15		8.25		1017		80		overcast clouds	2023-05-10 05:41:19	2023-05-10 20:51:59
Cairo		31		4.12		1008		23		clear sky	2023-05-10 04:05:19	2023-05-10 17:37:41

In [22]:
# Set the API endpoint URL and API key.
endpoint_url = "https://api.openweathermap.org/data/3.0/onecall/timemachine?dt=642353567"

# Define a list of coordinates for different locations
locations = [
    {'name': 'London', 'lat': 51.6553, 'lon': -0.396},
    {'name': 'Truro', 'lat': 50.2633173, 'lon': -5.0518107},
    {'name': 'Cairo', 'lat': 30.0443879, 'lon': 31.2357257},
]

# Create an empty list to store the weather data for each location.
hist_weather_data = []

# Loop through each location and get its weather data.
for loc in locations:
    # Set the API parameters.
    params = {
        "lat": loc['lat'],
        "lon": loc['lon'],
        "units": "metric",
        "exclude": "minutely,hourly,daily",
        "appid": API_key
    }

    # Send a GET request to the API endpoint and store the response.
    response = requests.get(endpoint_url, params=params)

    # Access the current weather data.
    historic = response.json()['data'][0]

    # Extract the relevant weather information.
    humidity = historic['humidity']
    pressure = historic['pressure']
    wind = historic['wind_speed']
    description = historic['weather'][0]['description']
    temp = int(round(historic['temp']))
    sunrise = datetime.fromtimestamp(historic['sunrise'], tz=pytz.utc).astimezone(pytz.timezone('Europe/London'))
    sunset = datetime.fromtimestamp(historic['sunset'], tz=pytz.utc).astimezone(pytz.timezone('Europe/London'))

    # Add the weather data to the list.
    hist_weather_data.append({
        'Location': loc['name'],
        'Temperature (°C)': temp,
        'Wind Speed (m/s)': wind,
        'Pressure (hPa)': pressure,
        'Humidity (%)': humidity,
        'Description': description,
        'Sunrise': sunrise,
        'Sunset': sunset
    })

# Print the weather data in a tabular format.
print("Location\tTemperature (°C)\tWind Speed (m/s)\tPressure (hPa)\tHumidity (%)\tDescription\tSunrise\t\t\t\tSunset")
for data in hist_weather_data:
    print(f"{data['Location']}\t\t{data['Temperature (°C)']}\t\t{data['Wind Speed (m/s)']}\t\t{data['Pressure (hPa)']}\t\t{data['Humidity (%)']}\t\t{data['Description']}\t{data['Sunrise'].strftime('%Y-%m-%d %H:%M:%S')}\t{data['Sunset'].strftime('%Y-%m-%d %H:%M:%S')}")

Location	Temperature (°C)	Wind Speed (m/s)	Pressure (hPa)	Humidity (%)	Description	Sunrise				Sunset
London		13		5.7		1011		54		light intensity shower rain	1990-05-10 05:16:53	1990-05-10 20:39:08
Truro		13		5.7		1015		57		scattered clouds	1990-05-10 05:40:35	1990-05-10 20:52:40
Cairo		25		5.1		1010		34		few clouds	1990-05-10 04:04:59	1990-05-10 17:37:58

In [23]:
# Finally, let's create a formatted DataFrame. 
# Create a data frame from the list of dictionaries.
df = pd.DataFrame(weather_data)

styled_df = df.style \
    .set_caption("Example DataFrame") \
    .set_properties(**{'text-align': 'center'}) \
    .set_table_styles([{'selector': 'th', 'props': [('text-align', 'center')]}]) \
    .background_gradient(cmap='viridis', low=0, high=1)

# display the styled DataFrame
display(styled_df)

In [24]:
# Finally, let's create a formatted DataFrame and export it as CSV. 
# Create a data frame from the list of dictionaries.
df2 = pd.DataFrame(hist_weather_data)
df2

,Location,Temperature (°C),Wind Speed (m/s),Pressure (hPa),Humidity (%),Description,Sunrise,Sunset
0,London,13,5.7,1011,54,light intensity shower rain,1990-05-10 05:16:53+01:00,1990-05-10 20:39:08+01:00
1,Truro,13,5.7,1015,57,scattered clouds,1990-05-10 05:40:35+01:00,1990-05-10 20:52:40+01:00
2,Cairo,25,5.1,1010,34,few clouds,1990-05-10 04:04:59+01:00,1990-05-10 17:37:58+01:00

In [25]:
# Concatenate the DataFrames.
df_concat = pd.concat([df, df2])

# View the output.
df_concat

,Location,Temperature (°C),Wind Speed (m/s),Pressure (hPa),Humidity (%),Description,Sunrise,Sunset
0,London,16,4.12,1008,75,light rain,2023-05-10 05:17:39+01:00,2023-05-10 20:38:24+01:00
1,Truro,15,8.25,1017,80,overcast clouds,2023-05-10 05:41:19+01:00,2023-05-10 20:51:59+01:00
2,Cairo,31,4.12,1008,23,clear sky,2023-05-10 04:05:19+01:00,2023-05-10 17:37:41+01:00
0,London,13,5.70,1011,54,light intensity shower rain,1990-05-10 05:16:53+01:00,1990-05-10 20:39:08+01:00
1,Truro,13,5.70,1015,57,scattered clouds,1990-05-10 05:40:35+01:00,1990-05-10 20:52:40+01:00
2,Cairo,25,5.10,1010,34,few clouds,1990-05-10 04:04:59+01:00,1990-05-10 17:37:58+01:00

# 9. Draw a conclusion- are there any significant differences in weather conditions now and in 1990?
London, Truro and Cairo are all warmer in May 2023 than in May 1990. The wind speed is higher in Truro now too, as well as the humidity.